### PR TITLE
Show most recently updated work first and only work updated in last 6 months

### PR DESCRIPTION
**Pull request by cillian**
Hi,
This implements some of the suggestions in #502.

work-to-be-done

### CODE REVIEW

**Comment by bhaugen** [comment]
@cillian thank you very much! Got any other plans, ideas, suggestions? Want to talk about them?

**Comment by cillian** [comment]
@bhaugen no problem, just having a look and getting my head around things at the moment.

Is there a database I could use locally that has more data in it than the OCP database? e.g. more resources/resource types etc. It might be easier to see how everything works if so.

**Comment by bhaugen** [comment]
How about this one? http://valdev.webfactional.com/

If you like that one, I'll get you a copy.

**Comment by cillian** [comment]
Yeah if that's ok that would be great thanks

**Comment by bhaugen** [comment]
Got it. Where should I put it so you can get it? Can you get things from google drive using your contact email on your website? It's 8.1 MB.

**Comment by cillian** [comment]
Good stuff thanks, yeah I should be able to pick up the link at that email.

**Comment by bhaugen** [comment]
Ok, sent email with link. Let me know if you have problems and I'll make it open to anybody with the link until you download it.

**Comment by cillian** [comment]
Got it!

**Pull request merged**
