### PR TITLE
Update NavMapCode.html

### PR DESCRIPTION
**Pull request by snowy13**
Plan work without recipe on navmap was a dead link

### CODE REVIEW

**Comment by fosterlynn** [comment]
Hey thanks!!

I'll merge the pull request, but also that has to be fixed on your data (because people can actually do whatever they like with their home page).

Go to Admin, take Home Page Layout, click on the object, make the same fix in the html code at the top (Banner).

**Comment by snowy13** [comment]
Thanks Lynn ;)

On Mon, Jun 27, 2016 at 1:36 PM, Lynn Foster <notifications@github.com>
wrote:

> Merged #509 <https://github.com/valnet/valuenetwork/pull/509>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/valnet/valuenetwork/pull/509#event-705271323>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHgbKqp0J85NTpyaJNJ9WBhAQlZjgqCjks5qQAodgaJpZM4I_Ua8>
> .
>



-- 
Jim Anastassiou
jim.anastassiou@gmail.com


Core Affiliate of Sensorica <http://www%2Csensorica.co/> - Profile
<http://www.sensorica.co/home/about-us/jim-anastassiou>
Administrator of ACES-CAKE <http://aces-cake.org>
jim@aces-cake.org

SENSORICA Montreal LabOnline
3485 Boul St-Laurent,
Montréal, QC H2X 2T6
(514) 418-8384

**Comment by fosterlynn** [comment]
Awesome to see a PR from you!

**Comment by snowy13** [comment]
No biggey, but it's a start ; )
You will see more in the future!

On Mon, Jun 27, 2016 at 3:14 PM, Lynn Foster <notifications@github.com>
wrote:

> Awesome to see a PR from you!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/valnet/valuenetwork/pull/509#issuecomment-228846030>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHgbKtClDOEKNau71VUUPgDr9MJJ2jWaks5qQCEogaJpZM4I_Ua8>
> .
>



-- 
Jim Anastassiou
jim.anastassiou@gmail.com


Core Affiliate of Sensorica <http://www%2Csensorica.co/> - Profile
<http://www.sensorica.co/home/about-us/jim-anastassiou>
Administrator of ACES-CAKE <http://aces-cake.org>
jim@aces-cake.org

SENSORICA Montreal LabOnline
3485 Boul St-Laurent,
Montréal, QC H2X 2T6
(514) 418-8384

**Pull request merged**
