### PR TITLE
Show most active projects on the homepage. #502

### PR DESCRIPTION
**Pull request by cillian**
This adds most active projects to the homepage. It adds them in a 4th column, not 100% sure if that's the best way yet.

### CODE REVIEW

**Comment by bhaugen** [comment]
Got a screenshot? If so, show it here, we can get some feedback.

Also: did you look at the [HomePageLayout model](https://github.com/valnet/valuenetwork/blob/master/valuenetwork/valueaccounting/models.py#L131)?

It's a cheap hacky way of making a configurable front page. The data-driven panels can be selected for use or not, or replaced by HTML text panels. That's also where we settled on 3 columns, which is a little rigid.
> It adds them in a 4th column, not 100% sure if that's the best way yet.

Yeah, me either. And I'm also not sure it is a good idea to continue with that rigid format of a fixed number of panels. So I'm also pretty sure it is not a good idea to change the model, go thru schema migrations, etc, just extending the same idea.

What would it take to make the column spans vary depending on the number of panels selected for use? So if they select only two of the panels, then the 3rd column wold be the most active projects?

Let me know it this is not understandable or doesn't make sense to you to do.

**Comment by TiberiusB** [comment]
Waw, this is a feature I was looking for for long time. I am eager to see
how it looks.

**Comment by bhaugen** [comment]
Hi @cillian - where are you at on this? Did my suggestions for improvement make sense to you? If so, got time to do them? 
If you think they make sense but you don't have time, let me know and I'll merge your PR anyway and then raise an issue for the improvements and Tibi can see how it looks.

**Comment by cillian** [comment]
Hi @bhaugen yes that makes sense for the panels to expand to fill the available space depending on what's enabled. It should behave like that now. The active projects panel is pretty basic, it just shows projects with activity in the last 6 months.

panels

**Comment by bhaugen** [comment]
Thanks a lot! Merging.

**Pull request merged**
